### ISSUE TITLE
Website Failure

### ISSUE THREAD

**Issue by WillXH** [cmbi/xssp-api#110]
The website was working smoothly like five days ago. Today I tried to generate a DSSP file with a PDB file and the website failed. Thanks for fixing the bug in advance!
![image](https://user-images.githubusercontent.com/105333050/183497498-1f4e9081-b88e-469a-86a0-e60cf7e37631.png)

**Comment by cbaakman** [comment]
Sorry about this. I fixed libcifpp.so.1. Currently I'm updating pdb, so that it will contain 7fje.

**Comment by WillXH** [comment]
Thank you for the response! Is the xssp service still accessible through [www.cmbi.umcn.nl/xssp](http://www.cmbi.umcn.nl/xssp)? I tried to visit the website but it says 404 Not Found.
