### ISSUE TITLE
Version on API and API example pages not shown correctly

### ISSUE THREAD

**Issue by touwwouter** [cmbi/xssp-api#73]
The version footer for the xssp version (#56) is also visible on the API and API example pages, without version number (bug). On the latter it overlaps with the code example (enhancement?).

**Comment by cbaakman** [comment]
It doesn't seem to overlap anymore. However, it's still there.

**Comment by touwwouter** [comment]
So, fixed?

**Comment by cbaakman** [comment]
The version number will be added in #91. Once this is merged, the issue is fully fixed.
