### ISSUE TITLE
API Create when input=sequence and output=HG_HSSP causes error

### ISSUE THREAD

**Issue by laurensvdwiel** [cmbi/xssp-api#81]
Using the following python code:

```
hg_sequence = 'MNGTEGPNFYVPFSNATGVVRSPFEYPQYYLAEPWQFSMLAAYMFLLIVLGFPINFLTLYVTVQHKKLRTPLNYILLNLAVADLFMVLGGFTSTLYTSLHGYFVFGPTGCNLEGFFATLGGEIALWSLVVLAIERYVVVCKPMSNFRFGENHAIMGVAFTWVMALACAAPPLAGWSRYIPEGLQCSCGIDYYTLKPEVNNESFVIYMFVVHFTIPMIIIFFCYGQLVFTVKEAAAQQQESATTQKAEKEVTRMVIIMVIAFLICWVPYASVAFYIFTHQGSNFGPIFMTIPAFFAKSAAIYNPVIYIMMNKQFRNCMLTTICCGKNPLGDDEASATVSKTETSQVAPA', rest_url= 'http://www.cmbi.umcn.nl/xssp/'
data = {'data': hg_sequence}
url_create = '{}api/create/sequence/hg_hssp/'.format(rest_url)
r = requests.post(url_create, params=data)
r.raise_for_status()
```

Provided the following error in python:
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://www.cmbi.umcn.nl/xssp/api/create/sequence/hg_hssp/?data=MNGTEGPNFYVPFSNATGVVRSPFEYPQYYLAEPWQFSMLAAYMFLLIVLGFPINFLTLYVTVQHKKLRTPLNYILLNLAVADLFMVLGGFTSTLYTSLHGYFVFGPTGCNLEGFFATLGGEIALWSLVVLAIERYVVVCKPMSNFRFGENHAIMGVAFTWVMALACAAPPLAGWSRYIPEGLQCSCGIDYYTLKPEVNNESFVIYMFVVHFTIPMIIIFFCYGQLVFTVKEAAAQQQESATTQKAEKEVTRMVIIMVIAFLICWVPYASVAFYIFTHQGSNFGPIFMTIPAFFAKSAAIYNPVIYIMMNKQFRNCMLTTICCGKNPLGDDEASATVSKTETSQVAPA

**Comment by cbaakman** [comment]
Running it like this results in a 202:
```
r = requests.post("http://www.cmbi.umcn.nl/xssp/api/create/sequence/hg_hssp/", data={'data': sequence})
```

**Comment by jonblack** [comment]
What Coos is saying is that you passed the POST data using the `params` keyword parameter instead of `data`.
