### ISSUE TITLE
failed without an error

### ISSUE THREAD

**Issue by cbaakman** [cmbi/xssp-api#87]
I frequently recieve e-mails about xssp-rest failing. However, the reported error is an empty string.
Can we make xssp report the actual error?

**Comment by jonblack** [comment]
We received almost 2000 error reports over the weekend with this problem. Can you look into it? Use the logs to see which jobs were being sent to try and reproduce it.

**Comment by cbaakman** [comment]
These particular errors seem to be raised whenever hsspconv is called.

**Comment by jonblack** [comment]
This is an issue in xssp. See the fix in https://github.com/cmbi/xssp/pull/92.
