### ISSUE TITLE
Footer covers output

### ISSUE THREAD

**Issue by jonblack** [cmbi/xssp-api#88]
The footer covers the output. HOPE has a nice footer that always remains at the bottom and out of the way of the main content. Copy this here.

**Comment by cbaakman** [comment]
Doesn't the page already have a footer with version number, what about this block: https://github.com/cmbi/xssp-api/blob/master/xssp_rest/frontend/templates/base.html#L86

**Comment by jonblack** [comment]
The problem is that the footer covers the output after a job is run rather than being below it.
